# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: dev-postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: local
